### ISSUE TITLE
Setup basic CLI

### ISSUE THREAD

**Issue by MorrisLaw** [digitalocean/go-workers2#29]
Create the foundation for a CLI to connect to `stats.go` data.

**Comment by sudaraka94** [comment]
Hi @MorrisLaw I am interested in working on this. Can you provide a bit more info on this?

**Comment by MorrisLaw** [comment]
Hey @sudaraka94 we'd like to have the `stats` data exposed through a CLI. Specifically, this data https://github.com/digitalocean/go-workers2/blob/master/stats.go#L50-L57

Does this help?

**Comment by sudaraka94** [comment]
I just need to clear some points,

- How should I present data ? (as a formatted text  or a json)
- I will provide a method which allows users to pass in `os.Args` which will allow commands like 
`appName stats`

Does this seems fine? Am I missing something?

**Comment by MorrisLaw** [comment]
Yeah that sounds fine @sudaraka94. I think having the data exposed as `json` would be useful. It should expose all of that `Stats` data, i.e.:
```
[
  {
    "manager_name": "some manager name",
    "processed": 24,
    "failed": 2,
    "jobs": {
      "worker_jobs": null
    },
    "enqueued": {
      "worker_jobs": 0
    },
    "retries": 2
  }
]
```

**Comment by sudaraka94** [comment]
Just one more thing, Is it okay to fetch the stats from the stat server, for the cli?

**Comment by MorrisLaw** [comment]
@stefannegrea wdyt?

**Comment by sudaraka94** [comment]
I was thinking of using unix sockets

**Comment by MorrisLaw** [comment]
Hey @sudaraka94. Are you able to elaborate how you would create this basic CLI using unix sockets?

We currently have an `http+json` implementation to get data from a server.

Unix sockets may be more work than need be.

**Comment by MorrisLaw** [comment]
The Stats code: https://github.com/digitalocean/go-workers2/blob/f6e32ba33f0f1daeb0569d1f7a5990bcfc95ff62/stats.go#L31

How to run the stats server locally:  https://github.com/digitalocean/go-workers2/blob/master/README.md

The code in that README calls the following function to start the server, locally, on a port you specify: https://github.com/digitalocean/go-workers2/blob/f6e32ba33f0f1daeb0569d1f7a5990bcfc95ff62/stats.go#L64

**Comment by stefannegrea** [comment]
PR #39 will resolve this issue.

**Comment by stefannegrea** [comment]
The PR has been merged, the project now has a CLI tool. Thanks @MorrisLaw for the contribution!
