### ISSUE TITLE
Update go-redis dependency

### ISSUE THREAD

**Issue by MorrisLaw** [digitalocean/go-workers2#31]
we're using a version that is no longer compatible

**Comment by alloro** [comment]
the latest release of go-redis currently (v6.15.6) does not use go.mod. Thats why you see +incompatible. I wouldn't recommend updating the dependency just to get rid of this marker behind the dependency. As far as I can see from go-redis is that with the next release you can just smoothly updating to v7 which will contain a go.mod file.

**Comment by stefannegrea** [comment]
This issue has now been resolved.
