### ISSUE TITLE
How does ProcessID option work?

### ISSUE THREAD

**Issue by slapec93** [digitalocean/go-workers2#45]
Hi, we're trying to use your library in one of our projects, where it's important to have reliable worker implementation. We're trying to figure out, what exactly the ProcessID option does (https://github.com/digitalocean/go-workers2/blob/master/options.go#L15). Can you please provide more information and explain what value should we use there?

**Comment by stefannegrea** [comment]
Helllo, sorry for the late reply but I need a few details to answer this question. The process id does not work very well for deployments with ephemeral instances. Are you able to restart each manager with the same id in case it fails (eg. OOM)?
